aws:
  dynamodb:
    endpoint: dynamodb.us-east-2.amazonaws.com
    region: us-east-2
    accessKey-local: ACESS_KEY
    secretKey-local: SECRET_KEY
    secret-arn: arn:aws:secretsmanager:us-east-2:339712897027:secret:userServiceDynamoDB-XWiqtf

logging:
  level:
    org.springframework: DEBUG

gateway:
  via-cep-endpoint: "https://viacep.com.br/ws/%s/json/"

security:
  secret: 123456[B@13[B@[B@13[B@1390a43a90a4[B@1390a43a3a1390a[B[B@1390a43a@13[B@1390[B@1390a43aa43a90a43a43a9[B@1390a43a0a43a
  expiration-time: 60_000
  token-prefix: Bearer
  header: Authorization
  rule-user: USER
  secret-arn: arn:aws:secretsmanager:us-east-2:339712897027:secret:secret_assinatura_token-q5kHc0