apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedidosml-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pedidosml
  template:
    metadata:
      labels:
        app: pedidosml
    spec:
      containers:
        - name: pedidosml
          image: leodocker01/pedidosml:latest # Sua imagem Docker
          ports:
            - containerPort: 8080
          env:
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret